### ISSUE TITLE
AnnotationTargetController not found

### ISSUE THREAD

**Issue by Frederic-P** [Daniel-KM/Omeka-S-module-Annotate#1]
Omeka S version: 1.2
Annotate version:  3.0.3
Annotate images and maps: 3.0.5-beta2
PHP version: 7.2.10
Ubuntu : 18.04 LTS

Problem:
I've started on a fresh instance of Omeka S and uploaded one item with media in an item set. When logged in as admin I can view the item > Describe . There I can draw polygons and add descriptions to segments of the media related to the item. When going as admin to that same item > Annotations I can see the newly made changes without issues.

When going to the site in another browser where I'm not logged in: site > browse > item, I can see the annotations I made, when clicking one those annotations I get an error message:

> Omeka S encountered an error
> Zend\Permissions\Acl\Exception\InvalidArgumentException
> Resource 'Omeka\Controller\Site\AnnotationTargetController' not found
> 
> Details:
> 
> Zend\Permissions\Acl\Exception\InvalidArgumentException: Resource 'Omeka\Controller\Site\AnnotationTargetController' not found in /var/www/html/omeka2/vendor/zendframework/zend-permissions-acl/src/Acl.php:291
> Stack trace:
> #0 /var/www/html/omeka2/vendor/zendframework/zend-permissions-acl/src/Acl.php(737): Zend\Permissions\Acl\Acl->getResource('Omeka\\Controlle...')
> #1 /var/www/html/omeka2/application/src/Permissions/Acl.php(92): Zend\Permissions\Acl\Acl->isAllowed(NULL, 'Omeka\\Controlle...', 'show')
> #2 /var/www/html/omeka2/application/src/Mvc/MvcListeners.php(434): Omeka\Permissions\Acl->userIsAllowed('Omeka\\Controlle...', 'show')
> #3 /var/www/html/omeka2/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Omeka\Mvc\MvcListeners->authorizeUserAgainstController(Object(Zend\Mvc\MvcEvent))
> #4 /var/www/html/omeka2/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
> #5 /var/www/html/omeka2/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
> #6 /var/www/html/omeka2/index.php(21): Zend\Mvc\Application->run()
> #7 {main}
> Powered by Omeka S 

Going back to the browser where I'm logged in I can add another annotation without problems. I then return to the browser where I'm not logged in and go one page back and refresh, I can see the latest annotation added to the item page; but when clicking it, I get the same error as above. 

Best regards.

EDIT:
I've checked the annotations when I'm logged in, and all of them are public.

**Comment by Daniel-KM** [comment]
Annotate and Cartography are still in development (but it's ending in a few time). The public part may be fixed with the version 3.0.4.

**Comment by Daniel-KM** [comment]
This is fixed in last version.
