### ISSUE TITLE
Mise à jour impossible

### ISSUE THREAD

**Issue by samszo** [Daniel-KM/Omeka-S-module-Annotate#2]
Avec les versions :
Omeka S : 2.2.1
Module Annotate : 3.1.3.1
Impossible de modifier une annotation : "There must be one annotation target at least."
Pour reproduire le problème :  
- créer manuellement une annotation
- éditer l'annotation
- enregistrer sans rien modifier

**Comment by Daniel-KM** [comment]
Merci de l'info. Normalement, on édite rarement directement, mais cela marche maintenant (version 3.1.3.3.)
