### ISSUE TITLE
only global administrator can annotate - 'Annotate\View\Helper\NormalizeDateTimeQuery' not found

### ISSUE THREAD

**Issue by sinanatra** [Daniel-KM/Omeka-S-module-Annotate#6]
I am using version 3.3.7.3, but I have noticed that only the global administrator can add annotations. All other users return an error, which does not appear in the logs. I went back to version 3.3.6 and the editor user receives this error again:

``` 
Error: Class 'Annotate\View\Helper\NormalizeDateTimeQuery' not found in /home/project/omeka-s/vendor/laminas/laminas-servicemanager/src/Factory/InvokableFactory.php:31
```

**Comment by Daniel-KM** [comment]
NormalizeDateTimeQuery is available since a very old version, it is probably related to a mix of versions.
